# Generated by Django 6.0.2 on 2026-02-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_workoutlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutLog',
        ),
    ]
